# Generated by Django 5.2 on 2025-04-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatconversation",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["sequence", "timestamp"]},
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sequence",
            field=models.IntegerField(default=0),
        ),
    ]
